IMAGE_TO_LINK = {
                'big_slant_bullseye.gif': 'https://media.giphy.com/media/l48SKQ8z69ji0Zf9t4/giphy.gif',
                'big_slant_circle.gif': 'https://media.giphy.com/media/xcDbZV4dEQPm5y9Tsg/giphy.gif',
                'big_slant_dots.gif': 'https://media.giphy.com/media/E3QIJy7q2BIffvLgyS/giphy.gif',
                'big_slant_down_parab.gif': 'https://media.giphy.com/media/x5zYRuPRsZU9QFY8Ns/giphy.gif',
                'big_slant_h_lines.gif': 'https://media.giphy.com/media/Bwxs6fL6fc2wSeVEph/giphy.gif',
                'big_slant_slant_down.gif': 'https://media.giphy.com/media/Rt1Iia8TM3qIQhDAwZ/giphy.gif',
                'big_slant_slant_up.gif': 'https://media.giphy.com/media/tsvtmpb0NiuLL1Hi6Q/giphy.gif',
                'big_slant_star.gif': 'https://media.giphy.com/media/tK7VoaOzfd7plACNit/giphy.gif',
                'big_slant_v_lines.gif': 'https://media.giphy.com/media/RVlLnEenBG1NlpGu0K/giphy.gif',
                'big_slant_wide_lines.gif': 'https://media.giphy.com/media/RVlLnEenBG1NlpGu0K/giphy.gif',
                'big_slant_x.gif': 'https://media.giphy.com/media/DXC5zkadGimdE4sETu/giphy.gif',
                'dino_bullseye.gif': 'https://media.giphy.com/media/d4hKq9Ss9lccTh2ZXs/giphy.gif',
                'dino_circle.gif': 'https://media.giphy.com/media/f1QOOsaayJGzN7AkJB/giphy.gif',
                'dino_dots.gif': 'https://media.giphy.com/media/PF43aEkCv65bblyQ1S/giphy.gif',
                'dino_down_parab.gif': 'https://media.giphy.com/media/Qm9L47Gco7kIeLSHjO/giphy.gif',
                'dino_h_lines.gif': 'https://media.giphy.com/media/BGZlgucmV2JC50bbsz/giphy.gif',
                'dino_high_lines.gif': 'https://media.giphy.com/media/6AjxBc37SJ6Ngq9uc8/giphy.gif',
                'dino_slant_down.gif': 'https://media.giphy.com/media/GHCFYFwTsVrGc3crBf/giphy.gif',
                'dino_slant_up.gif': 'https://media.giphy.com/media/QQfXSHfFisyEd3M3J4/giphy.gif',
                'dino_star.gif': 'https://media.giphy.com/media/RGkV2Jx23Nnhw9SWSK/giphy.gif',
                'dino_v_lines.gif': 'https://media.giphy.com/media/VpNEpp4qd8yirlx1Fz/giphy.gif',
                'dino_wide_lines.gif': 'https://media.giphy.com/media/M5Mrl4Sb5LbUo4gcM2/giphy.gif',
                'dino_x.gif': 'https://media.giphy.com/media/M8HetEV2bQa3NFu7Wv/giphy.gif'
                }